[phases.setup]
nixPkgs = [
    "python311",
    "pango",
    "fontconfig", 
    "cairo",
    "gdk-pixbuf",
    "glib",
    "gobject-introspection",
    "harfbuzz",
    "freetype",
    "libffi",
    "zlib"
]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[variables]
GI_TYPELIB_PATH = "/nix/store"
